(define _pass 0)
(define _fail 0)

(define (assert desc expected actual)
  (if (equal? expected actual)
      (set! _pass (+ _pass 1))
      (begin
        (set! _fail (+ _fail 1))
        (display "  FAIL: ")
        (display desc)
        (display " — expected ")
        (write expected)
        (display ", got ")
        (write actual)
        (newline))))

(define (summary)
  (display _pass)
  (display " passed, ")
  (display _fail)
  (display " failed")
  (newline)
  (if (> _fail 0)
      (error "tests failed")))
