(define (make-suite)
  (let ((passed 0)
        (failed 0))
    (define (assert description expected actual)
      (if (equal? expected actual)
          (set! passed (+ passed 1))
          (begin
            (set! failed (+ failed 1))
            (display "  FAIL: ")
            (display description)
            (display ": expected ")
            (write expected)
            (display ", got ")
            (write actual)
            (newline))))

    (define (finish)
      (display passed)
      (display " passed, ")
      (display failed)
      (display " failed")
      (newline)
      (if (> failed 0)
          (error "tests failed")))

    (lambda (message)
      (case message
        ((assert) assert)
        ((finish) (finish))
        (else (error "unknown suite message" message))))))

(load "tests/test_arithmetic.scm")
(load "tests/test_chars.scm")
(load "tests/test_closures.scm")
(load "tests/test_errors.scm")
(load "tests/test_integration.scm")
(load "tests/test_lists.scm")
(load "tests/test_macros.scm")
(load "tests/test_numbers.scm")
(load "tests/test_preamble.scm")
(load "tests/test_special_forms.scm")
(load "tests/test_streams.scm")
(load "tests/test_stress.scm")
(load "tests/test_strings.scm")
(load "tests/test_tailcalls.scm")
(load "tests/test_vectors.scm")

(define tests
  (list
    (cons 'arithmetic test-arithmetic)
    (cons 'chars test-chars)
    (cons 'closures test-closures)
    (cons 'errors test-errors)
    (cons 'integration test-integration)
    (cons 'lists test-lists)
    (cons 'macros test-macros)
    (cons 'numbers test-numbers)
    (cons 'preamble test-preamble)
    (cons 'special-forms test-special-forms)
    (cons 'streams test-streams)
    (cons 'stress test-stress)
    (cons 'strings test-strings)
    (cons 'tailcalls test-tailcalls)
    (cons 'vectors test-vectors)))

(define (select-tests names)
  (if (null? names)
      tests
      (map
        (lambda (name)
          (let ((test (assv name tests)))
            (if test
                test
                (error "unknown test" name))))
        names)))

(define (run-tests names)
  (let ((suite (make-suite)))
    (for-each
      (lambda (test)
        (display "RUN   ")
        (display (car test))
        (newline)
        ((cdr test) suite))
      (select-tests names))
    (suite 'finish)))
