(assert "string-length" 5 (string-length "hello"))
(assert "string-ref" "e" (string-ref "hello" 1))
(assert "substring" "ell" (substring "hello" 1 4))
(assert "string-append" "hello world" (string-append "hello" " " "world"))
(assert "string=?" #t (string=? "abc" "abc"))
(assert "string=? false" #f (string=? "abc" "def"))
(assert "number->string" "42" (number->string 42))
(assert "string->number" 42 (string->number "42"))
(assert "symbol->string" "foo" (symbol->string 'foo))
(assert "string->symbol" 'foo (string->symbol "foo"))
(assert "string?" #t (string? "hi"))
(assert "string? false" #f (string? 42))
(summary)
