(assert "cons" '(1 . 2) (cons 1 2))
(assert "car" 1 (car '(1 2 3)))
(assert "cdr" '(2 3) (cdr '(1 2 3)))
(assert "list" '(1 2 3) (list 1 2 3))
(assert "length" 3 (length '(1 2 3)))
(assert "length empty" 0 (length '()))
(assert "list-ref" 'c (list-ref '(a b c d) 2))
(assert "null?" #t (null? '()))
(assert "null? false" #f (null? '(1)))
(assert "pair?" #t (pair? '(1 2)))
(assert "pair? false" #f (pair? 5))
(assert "list?" #t (list? '(1 2 3)))
(assert "list? dotted" #f (list? '(1 . 2)))

(define p (cons 1 2))
(set-car! p 10)
(assert "set-car!" 10 (car p))
(set-cdr! p 20)
(assert "set-cdr!" 20 (cdr p))

(summary)
